### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by sumit8340**
"node" : "14.21.3"

Closes 

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by sumit8340** [comment]
hi

**Comment by Anshuman2121** [comment]
Don't add exact version rather add just major version like 14. 

Also in the readme file add which nodejs version to use at appropriate place

**Comment by sumit8340** [comment]
package.json file is refferred on readme file.That's why i made correction in package.json

**Comment by sumit8340** [comment]
line 21
*Install development dependencies. Note: Check the package.json engine for our tested and supported node versions.

**Pull request closed without merging**
